stages:
  - lint
  - build
  - deploy

variables:
  DOCKER_IMAGE: "registry.gitlab.com/$CI_PROJECT_PATH/nginx-demo"
  KUBECONFIG: "/root/.kube/config"

lint:
  stage: lint
  image: hashicorp/terraform:1.9
  script:
    - terraform fmt -check || true
    - terraform validate || true

build:
  stage: build
  image: docker:24
  services:
    - docker:dind
  script:
    - docker build -t $DOCKER_IMAGE:$CI_COMMIT_SHORT_SHA .
    - docker push $DOCKER_IMAGE:$CI_COMMIT_SHORT_SHA
  only:
    - main

deploy:
  stage: deploy
  image: bitnami/kubectl:latest
  script:
    - kubectl apply -n argocd -f gitops/app-argocd-helm.yaml
  only:
    - main
